import { NOTATION_TO_TYPES } from '../src/constants';

const standardVariants = {
    'EGFR:e.20_21ins': {
        break1Start: {
            '@class': 'ExonicPosition',
            pos: 20,
            prefix: 'e',
        },
        break1Repr: 'e.20',
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 21,
            prefix: 'e',
        },
        break2Repr: 'e.21',
        prefix: 'e',
        reference1: 'EGFR',
        type: NOTATION_TO_TYPES.ins,
    },
    'KRAS:p.G12D': {
        break1Start: {
            '@class': 'ProteinPosition',
            pos: 12,
            prefix: 'p',
            refAA: 'G',
        },
        break1Repr: 'p.G12',
        prefix: 'p',
        reference1: 'KRAS',
        type: NOTATION_TO_TYPES.mis,
        untemplatedSeq: 'D',
    },
};

// Actual fusion variant with legacy notation (KBDEV-974)
const legacyNomenclatureFusionVariants = {
    '(ATP1B1,NRG1):fusion(g.169080736,g.32453346)': {
        reference1: 'ATP1B1',
        reference2: 'NRG1',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'GenomicPosition',
            pos: 169080736,
            prefix: 'g',
        },
        break1Repr: 'g.169080736',
        break2Start: {
            '@class': 'GenomicPosition',
            pos: 32453346,
            prefix: 'g',
        },
        break2Repr: 'g.32453346',
        noFeatures: false,
        prefix: 'g',
    },
    '(ENST00000357447,ENST00000371953):fusion(c.1118,c.165)': {
        reference1: 'ENST00000357447',
        reference2: 'ENST00000371953',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'CdsPosition',
            pos: 1118,
            prefix: 'c',
            offset: 0,
        },
        break1Repr: 'c.1118',
        break2Start: {
            '@class': 'CdsPosition',
            pos: 165,
            prefix: 'c',
            offset: 0,
        },
        break2Repr: 'c.165',
        noFeatures: false,
        prefix: 'c',
    },
    '(COL1A1,PDGFB):fusion(r.2354,r.852)': {
        reference1: 'COL1A1',
        reference2: 'PDGFB',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'RnaPosition',
            pos: 2354,
            prefix: 'r',
            offset: 0,
        },
        break1Repr: 'r.2354',
        break2Start: {
            '@class': 'RnaPosition',
            pos: 852,
            prefix: 'r',
            offset: 0,
        },
        break2Repr: 'r.852',
        noFeatures: false,
        prefix: 'r',
    },
    '(CLTC,ALK):fusion(e.30,e.20)': {
        reference1: 'CLTC',
        reference2: 'ALK',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'ExonicPosition',
            pos: 30,
            prefix: 'e',
        },
        break1Repr: 'e.30',
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 20,
            prefix: 'e',
        },
        break2Repr: 'e.20',
        noFeatures: false,
        prefix: 'e',
    },
    '(ZNF532,NUTM1):fusion(p.?4,e.2)': {
        reference1: 'ZNF532',
        reference2: 'NUTM1',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'ProteinPosition',
            pos: 4,
            prefix: 'p',
            longRefAA: null,
            refAA: null,
        },
        break1Repr: 'p.?4',
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 2,
            prefix: 'e',
        },
        break2Repr: 'e.2',
        noFeatures: false,
        prefix: null,
    },
    '(CDH1,LARS):fusion(i.2,e.17)': {
        reference1: 'CDH1',
        reference2: 'LARS',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'IntronicPosition',
            pos: 2,
            prefix: 'i',
        },
        break1Repr: 'i.2',
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 17,
            prefix: 'e',
        },
        break2Repr: 'e.17',
        noFeatures: false,
        prefix: null,
    },
    '(chr3,BRAF):fusion(y.p26.3,e.4)': {
        reference1: 'chr3',
        reference2: 'BRAF',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            arm: 'p',
            majorBand: 26,
            minorBand: 3,
            '@class': 'CytobandPosition',
            prefix: 'y',
        },
        break1Repr: 'y.p26.3',
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 4,
            prefix: 'e',
        },
        break2Repr: 'e.4',
        noFeatures: false,
        prefix: null,
    },
};

// New fusion nomenclature (KBDEV-974)
const newNomenclatureFusionVariants = {
    'ATP1B1:g.?_169080736::NRG1:g.32453346_?': {
        reference1: 'ATP1B1',
        reference2: 'NRG1',
        multiFeature: true,
        type: NOTATION_TO_TYPES.fusion,
        break1Start: {
            '@class': 'GenomicPosition',
            pos: null,
            prefix: 'g',
        },
        break1End: {
            '@class': 'GenomicPosition',
            pos: 169080736,
            prefix: 'g',
        },
        break1Repr: 'g.?_169080736',
        break2End: {
            '@class': 'GenomicPosition',
            pos: null,
            prefix: 'g',
        },
        break2Start: {
            '@class': 'GenomicPosition',
            pos: 32453346,
            prefix: 'g',
        },
        break2Repr: 'g.32453346_?',
        noFeatures: false,
        prefix: 'g',
    },
    'ENST00000357447:c.?_1118::ENST00000371953:c.165_?': {
        reference1: 'ENST00000357447',
        reference2: 'ENST00000371953',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'CdsPosition',
            pos: null,
            prefix: 'c',
            offset: 0,
        },
        break1End: {
            '@class': 'CdsPosition',
            pos: 1118,
            prefix: 'c',
            offset: 0,
        },
        break1Repr: 'c.?_1118',
        break2End: {
            '@class': 'CdsPosition',
            pos: null,
            prefix: 'c',
            offset: 0,
        },
        break2Start: {
            '@class': 'CdsPosition',
            pos: 165,
            prefix: 'c',
            offset: 0,
        },
        break2Repr: 'c.165_?',
        noFeatures: false,
        prefix: 'c',
    },
    'COL1A1:r.?_2354::PDGFB:r.852_?': {
        reference1: 'COL1A1',
        reference2: 'PDGFB',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'RnaPosition',
            pos: null,
            prefix: 'r',
            offset: 0,
        },
        break1End: {
            '@class': 'RnaPosition',
            pos: 2354,
            prefix: 'r',
            offset: 0,
        },
        break1Repr: 'r.?_2354',
        break2End: {
            '@class': 'RnaPosition',
            pos: null,
            prefix: 'r',
            offset: 0,
        },
        break2Start: {
            '@class': 'RnaPosition',
            pos: 852,
            prefix: 'r',
            offset: 0,
        },
        break2Repr: 'r.852_?',
        noFeatures: false,
        prefix: 'r',
    },
    'CLTC:e.?_30::ALK:e.20_?': {
        reference1: 'CLTC',
        reference2: 'ALK',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'ExonicPosition',
            pos: null,
            prefix: 'e',
        },
        break1End: {
            '@class': 'ExonicPosition',
            pos: 30,
            prefix: 'e',
        },
        break1Repr: 'e.?_30',
        break2End: {
            '@class': 'ExonicPosition',
            pos: null,
            prefix: 'e',
        },
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 20,
            prefix: 'e',
        },
        break2Repr: 'e.20_?',
        noFeatures: false,
        prefix: 'e',
    },
    'ZNF532:p.??_?4::NUTM1:e.2_?': {
        reference1: 'ZNF532',
        reference2: 'NUTM1',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'ProteinPosition',
            pos: null,
            prefix: 'p',
            longRefAA: null,
            refAA: null,
        },
        break1End: {
            '@class': 'ProteinPosition',
            pos: 4,
            prefix: 'p',
            longRefAA: null,
            refAA: null,
        },
        break1Repr: 'p.??_?4',
        break2End: {
            '@class': 'ExonicPosition',
            pos: null,
            prefix: 'e',
        },
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 2,
            prefix: 'e',
        },
        break2Repr: 'e.2_?',
        noFeatures: false,
        prefix: null,
    },
    'CDH1:i.?_2::LARS:e.17_?': {
        reference1: 'CDH1',
        reference2: 'LARS',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'IntronicPosition',
            pos: null,
            prefix: 'i',
        },
        break1End: {
            '@class': 'IntronicPosition',
            pos: 2,
            prefix: 'i',
        },
        break1Repr: 'i.?_2',
        break2End: {
            '@class': 'ExonicPosition',
            pos: null,
            prefix: 'e',
        },
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 17,
            prefix: 'e',
        },
        break2Repr: 'e.17_?',
        noFeatures: false,
        prefix: null,
    },
    'chr3:y.p_p26.3::BRAF:e.4_?': {
        reference1: 'chr3',
        reference2: 'BRAF',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            arm: 'p',
            '@class': 'CytobandPosition',
            prefix: 'y',
        },
        break1End: {
            arm: 'p',
            majorBand: 26,
            minorBand: 3,
            '@class': 'CytobandPosition',
            prefix: 'y',
        },
        break1Repr: 'y.p_p26.3',
        break2End: {
            '@class': 'ExonicPosition',
            pos: null,
            prefix: 'e',
        },
        break2Start: {
            '@class': 'ExonicPosition',
            pos: 4,
            prefix: 'e',
        },
        break2Repr: 'e.4_?',
        noFeatures: false,
        prefix: null,
    },
    'EPCAM:r.?_555::GUAUGAUUUUUUAAUAA::MSH2:r.212_?': {
        reference1: 'EPCAM',
        reference2: 'MSH2',
        multiFeature: true,
        type: 'fusion',
        break1Start: {
            '@class': 'RnaPosition',
            pos: null,
            prefix: 'r',
            offset: 0,
        },
        break1End: {
            '@class': 'RnaPosition',
            pos: 555,
            prefix: 'r',
            offset: 0,
        },
        break1Repr: 'r.?_555',
        break2End: {
            '@class': 'RnaPosition',
            pos: null,
            prefix: 'r',
            offset: 0,
        },
        break2Start: {
            '@class': 'RnaPosition',
            pos: 212,
            prefix: 'r',
            offset: 0,
        },
        break2Repr: 'r.212_?',
        untemplatedSeq: 'GUAUGAUUUUUUAAUAA',
        untemplatedSeqSize: 17,
        noFeatures: false,
        prefix: 'r',
    },
};

export default {
    legacyNomenclatureFusionVariants,
    newNomenclatureFusionVariants,
    standardVariants,
};
